### ISSUE TITLE
Importing TabularExplainer

### ISSUE THREAD

**Issue by ri3017** [interpretml/interpret-community#201] opened 2020-04-06 10:15 UTC
**Describe the bug**
Hi! I have a problem when importing TabularExplainer ( I am getting this error "Cannot find reference "TabularExplainer" in '__init__.py' "). I am using PyCharm as IDEA and anaconda3.

**To Reproduce**
1. Go to 'anacondaprompt' (base environment)
2. pip install interpret-community
3. going to the Pycharm project
4. from interpret.ext.blackbox import TabularExplainer
5. the import throws the error

**Comment by imatiach-msft** [comment] 2020-04-06 15:27
hi @ri3017 , sorry about the trouble you are having.
Can you run python directly from the environment and try to run that:

```
PS C:\interpret-community> activate sh
(sh) PS C:\interpret-community> python
Python 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 18:50:55) [MSC v.1915 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from interpret.ext.blackbox import TabularExplainer
>>>
```

Also, can you please send us the "pip freeze" output for your environment.

Are you able to run:
from interpret_community.tabular_explainer import TabularExplainer

If so, this may be a problem with the extension.  If you send the full output of:

pip uninstall interpret-community
pip install interpret-community

That may help determine why the extension system is breaking (a warning will be printed out during installation).

**Comment by imatiach-msft** [comment] 2020-04-20 15:49
ping @ri3017 did my suggestions help resolve the issue?

**Comment by imatiach-msft** [comment] 2020-05-05 03:01
gentle ping @ri3017

**Comment by imatiach-msft** [comment] 2020-06-23 22:16
gentle ping @ri3017

**Comment by minarastgar** [comment] 2021-01-16 02:06
I have the same issue and your suggestions did not help, unfortunately. thanks in advance for your jelp

**Comment by imatiach-msft** [comment] 2021-12-30 15:41
Closing this issue as it is usually caused by a problem in the python environment with bad package versions installed.  If someone sees this again, please post your pip freeze file, which can help diagnose what package versions are incompatible and cause this error, the issue is very environment specific.

**Closed by imatiach-msft** 2021-12-30 15:41 UTC
