### ISSUE TITLE
NB VM does not always display, even with refresh

### ISSUE THREAD

**Issue by bethz** [interpretml/interpret-community#81] opened 2019-10-31 15:34 UTC
**Describe the bug**
Run any nb in ml.azure.com and the dashboard frequently does not display.

**To Reproduce**
1. run any notebook in ml.azure.com
- this is NOT when Jupyter or Jupyter lab is selected separately

**Expected behavior**
Expect to see dashboard

**Desktop (please complete the following information):**
Chrome

**Comment by pvillacorta-stratio** [comment] 2020-05-22 12:47
I am facing the same issue in JupyterLab outside Azure (not using Azure at all). When calling `ExplanationDashboard`, after a while of computations I get a blank output instead of the actual dashboard. I have tried restarting the kernel but seems not to work for some reason, although I made it work in the past.

**Comment by rihorn2** [comment] 2020-05-22 14:54
Hi, what version of interpret community are you using, this should be working in the latest release. Please update and let us know if the latest version is not displaying in jupyter labs.

**Comment by imatiach-msft** [comment] 2020-05-22 14:59
@pvillacorta-stratio  Also, do you see any error messages anywhere?  Maybe there was an error logged in the browser's debug tools?  If you are on the latest package, are you running one of our samples or your own code?

**Comment by pvillacorta-stratio** [comment] 2020-05-22 16:13
Thanks for your prompt replies! Yes, I am using the last version, 0.11.1 of interpret_community and 0.1.22 of interpret. I get no error, simply the code runs for a short while (the same as when the dashboard is displayed correctly) but then shows a big blank space (approx the size of the dashboard, but blank) and then, the cell output `<interpret_community.widget.explanation_dashboard.ExplanationDashboard at 0x7f82392a8d30>`

It is a very simple code to interpret a RandomForest model from sklearn:
```
from interpret_community.tabular_explainer import TabularExplainer

tabularExplainer = TabularExplainer(rf_model, 
                          X_train, 
                          features=X_train.columns, 
                          classes=[0, 1])
tabular_global_explanation = tabularExplainer.explain_global(X_train)

from interpret_community.widget import ExplanationDashboard
ExplanationDashboard(tabular_global_explanation, rf_model, datasetX = X_train)
```
At first I thought there might be an interaction with `shap.initjs()` from the shap package, but now I am having the issue even if I restart the kernel and do not run the initjs() command

**Comment by imatiach-msft** [comment] 2020-05-22 16:25
@pvillacorta-stratio does the issue appear on all browsers (chrome, edge, firefox, etc)?  Just wondering if the issue appears in all browsers.

```I thought there might be an interaction with shap.initjs()```

Probably not, that's a completely different visualization which we don't use/leverage.

**Comment by rihorn2** [comment] 2020-05-22 17:03
You mention that it is rendering a big cell with nothing in it, is there a scroll bar, and can you scroll to the upper left in case there is some error being logged. I have seen this behavior when some errors are rendered, that it prints the error and then renders a large empty div.

**Comment by pvillacorta-stratio** [comment] 2020-05-22 17:17
Hi both, 
Thanks again for your replies. There is no scroll, neither horizontal or vertical. Just the "Open in new tab" message, which does not work because I am running in a remote environment and tries to open localhost. Interestingly, I was able to do it in the past, although I had also met this problem even before. There must be something I am doing that prevents the dashboard from displaying correctly, but only some times.

**Comment by rihorn2** [comment] 2020-05-22 18:00
Ah, the issue will be the remote environment. Given that it is a remote environment, it should not be displaying the 'Open in new tab' except in Azure, so there is an issue detecting that where you are running is a remote environment. What cloud environment are you using, it must be one we haven't tested for previously?

**Comment by pvillacorta-stratio** [comment] 2020-05-22 18:23
I am not sure, let me check with the system admin. Anyway, the issue is not about opening a new tab, which is not relevant for me, but about displaying the dashboard inside the notebook. I was able to make it run but seems to have stopped working for some reason. I had the same issue in the past and still don't know why on a different day it came to work again...

**Comment by imatiach-msft** [comment] 2021-08-16 22:29
Closing this issue as this bug is very old and we haven't had this issue recently.  If anyone is still seeing this please open a new issue instead of reopening this one on the repository:
https://github.com/microsoft/responsible-ai-widgets

**Closed by imatiach-msft** 2021-08-16 22:29 UTC
Labels: bug
